Code spell checker 및 merlin 과 feather 에 공통으로 사용되는 룰 추가
koreacreditdata/eslint-config pull request #13
Opened 2021-07-02 04:07 UTC by parkoon

### 작업 내용
- eslint code spell checker 적용
- merlin 및 feather 공통 룰 추가

2021-07-05 03:58 UTC, ong-ar commented on package.json
> +  "version": "0.3.2",
현재 브랜치 전략이 없는 상황이라 같이 가도 괜찮을 것 같긴 합니다만,
패키지 버전업은 작업 PR 과는 따로 가는 것이 좋지 않을까 싶습니다. (개인의견)

2021-07-05 03:58 UTC, ong-ar approved these changes

2021-07-05 05:31 UTC, spilist requested changes
고생하셨습니다. 슬랙으로 전달드린 부분, 그리고 룰마다 comment 남기는 거 부탁드려요~

2021-07-05 05:31 UTC, spilist commented on package.json
> +  "version": "0.3.2",
저도 PR 브랜치는 버전을 올리지 않고, 버전 올리는 (+ 태그 붙은) develop 브랜치의 커밋이라든가가 따로 있는 게 더 적절하다고 생각합니다~

2021-07-06 02:40 UTC, J132134 commented on package.json
> +  "version": "0.3.2",
이 PR merge 이전에 다른 PR이 먼저 퍼블리시 되면 다시 버전이 낮아질 수도 있겠네요 ㅎㅎ

2021-07-06 02:48 UTC, J132134 requested changes

2021-07-06 02:48 UTC, J132134 commented on react.js
> +    "react/button-has-type": "off",
이건 왜 들어간걸까요?! `<button type="button">` 은 필요한 것 같습니다!

2021-07-06 02:48 UTC, J132134 commented on spellchecker.js
> +    ],
```suggestion
    "spellcheck/spell-checker": ["warn"],
```

이 레포가 유지보수가 활발한게 아니고, 어차피 대부분의 사용처에서 override할거라 굳이 안넣어도 될 것 같아요.

2021-07-06 02:48 UTC, J132134 commented on package.json
> +  "version": "0.3.2",
```suggestion
  "version": "0.3.1",
```

2021-07-07 08:48 UTC, J132134 commented on react.js
> +    "react/button-has-type": "off",
7/7 팀미팅에서 feather 의 Button 컴포넌트에서 필요해서 추가됐던 것으로 파악됨
-> 여기서는 제거하고 feather에만 두거나, Button 컴포넌트 파일에서만 주석으로 disable 해도 될 것 같습니다!

2021-07-07 09:24 UTC, parkoon commented on react.js
> +    "react/button-has-type": "off",
@J132134 오, 먼저 코멘트 남겨주셨네요! 감사합니다.

2021-07-07 09:32 UTC, parkoon commented on spellchecker.js
> +    ],
@J132134 7/7 팀미팅에서 얘기 나눴던것 처럼
`comments` 와 `ignoreRequire` 만 남겨놓겠습니다.

2021-07-07 14:01 UTC, spilist approved these changes
룰 코멘트 다는 목적은 "이 플러그인이 이 용도임" 이라기보다 "(이 플러그인은 이런 용도인데) 이렇게 사용하는 이유는 이것임" 이 되어야 해서, 지금 달아두신 코멘트가 좀 부적절한 부분들이 있네요. 이건 제가 업데이트해서 머지하겠습니다. 고생하셨어요~

는 제이든이 포크뜬 브랜치에서 온 PR이라 그건 어렵겠군요. 머지 후 업데이트해둘게요.

2021-07-07 14:02 UTC, merged

2021-07-07 16:45 UTC, J132134 reviewed
이미 머지되었지만 그래도 추가 의견 달아보았습니다.

2021-07-07 16:45 UTC, J132134 commented on typescript.js
> +
```suggestion
```